#%RAML 1.0
title: MUA-eService
version: v1
baseUri: http://mua.com
mediaType: application/json

types:
  responseData: !include flightDetails.raml

/flights:
  get:
    displayName: "Select flights by Airline and Destination"
    queryParameters:
      airline: 
        type: string
        required: true
      destination:
        type: string
        required: true
    responses:
      200:
        body:
          responseData  
      404:
        body:
          application/json:
            example:
              {"message" : "Flight Not Found"}

  /all:
    get:
      displayName: "Retrieve All available flights"
      responses:
        200:
          body:
            responseData
  /of:
    /united:
      get:
        displayName: "Flights of United Only"
        responses:
          200:
            body:
              responseData
  
    /american:
      get:
        displayName: "Flights of American Only"
        responses:
          200:
            body:
              responseData
  
    /delta:
      get:
        displayName: "Flights of DELTA Only"
        responses:
          200:
            body:
              responseData

    /{airlineID}/{destination}:
        get:
          displayName: "Flights by Airline and Destination "
          responses:
            200:
              body:
                responseData
          